spring.application.name=paciente
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:pacientesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

springdoc.swagger-ui.path=/swagger-ui.html